name: DBT Base Environment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: DBT Runner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run DBT
        run: |
          dbt deps
          dbt seed --target ${{ env.DBT_BASE_TARGET }} --target-path target-base
          dbt run --target ${{ env.DBT_BASE_TARGET }} --target-path target-base
          dbt docs generate --target ${{ env.DBT_BASE_TARGET }} --target-path target-base
          ls -la
        env:
          DBT_BASE_TARGET: "motherDuckProd"
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }} # Set these in your repository secrets

      - name: Package DBT artifacts
        run: |
          tar -czvf dbt-artifacts.tar.gz target-base jaffle_shop.duckdb
          mv dbt-artifacts.tar.gz $GITHUB_WORKSPACE/${{ github.sha }}.tar.gz

      - name: Upload to S3
        run: |
          aws s3 cp $GITHUB_WORKSPACE/${{ github.sha }}.tar.gz s3://${{ env.AWS_S3_BUCKET }}/${{ github.sha }}.tar.gz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # Set these in your repository secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Set these in your repository secrets
          AWS_REGION: ${{ secrets.AWS_REGION }} # Set these in your repository secrets
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} # Set these in your repository secrets
