name: Jaffle Shop Recce CI

on:
  pull_request:
    branches: [main]

jobs:
  check-pull-request:
    name: Check pull request by Recce CI
    runs-on: ubuntu-latest
    steps:     
      - name: Run Recce CI
        run: |
           echo "${GITHUB_TOKEN: -6}"
           curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user
        env:
          GITHUB_TOKEN: ${{ secrets.RECCE_CLOUD_TOKEN }}
          RECCE_STATE_PASSWORD: ${{ vars.RECCE_STATE_PASSWORD}}

      